on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Create screen-blend.jar
        run: |
          javac ./com/github/cb0s/movieblend/MovieScreen.java
          mkdir staging
          echo $'Manifest-Version: 1.0\r\nMain-Class: com.github.cb0s.movieblend.MovieScreen\r\nClass-Path: .' > MANIFEST.MF
          jar cfm staging/screen-blend.jar ./MANIFEST.MF ./com/github/cb0s/movieblend/MovieScreen.class
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          path: staging
